spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/hospital
    username: sa
    password: test2560

  jpa:
    show_spl: true
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000